#!/bin/bash

echo -ne "Please make sure you install virtualenvwrapper in your system\n\n"
echo -ne "  $ sudo pip install virtualenvwrapper\n\n"
echo -ne "  or\n\n"
echo -ne "  $ sudo pip3 install virtualenvwrapper\n"
echo -ne "\n"
echo -ne "Installing pip-save..."

# ~/.zshrc, ~/.bashrc
SHELL_RC_FILE="$HOME/.$(basename $SHELL)rc"
COUNT=0
IFS=':' read -ra PATHS <<< "$PATH"

for p in "${PATHS[@]}"; do
	if [[ $p == "$HOME/bin" || $p == "~/bin" ]]
	then
		COUNT=$(($COUNT+1))
	fi
done

if [[ $COUNT == 0 ]]
then
	echo 'export PATH=$HOME/bin:$PATH' >> $SHELL_RC_FILE
fi

[ $(grep -e "pipsave_line" ~/.zshrc | wc -l) == 0 ] && echo '[ -f ~/.pipsave_cd ] && source ~/.pipsave_cd # pipsave_line' >> $SHELL_RC_FILE

[ -z $WORKON_HOME ] && echo "export WORKON_HOME=~/.virtualenvs" >> $SHELL_RC_FILE
[ -z $VIRTUALENVWRAPPER_SCRIPT ] && echo "source /usr/local/bin/virtualenvwrapper.sh" >> $SHELL_RC_FILE

curl -sSLk -o $HOME/bin/pip3 "https://raw.githubusercontent.com/abhiomkar/pip-save/master/bin/pip3" && \
curl -sSLk -o $HOME/.pipsave_cd "https://raw.githubusercontent.com/abhiomkar/pip-save/master/src/pipsave_cd" && \
echo -ne "\n>>> Installation successful"
chmod +x $HOME/bin/pip3
