#!/bin/bash

echo -ne "Please make sure you install virtualenvwrapper in your system\n\n"
echo -ne "  $ sudo pip install virtualenvwrapper\n\n"
echo -ne "  or\n\n"
echo -ne "  $ sudo pip3 install virtualenvwrapper\n"
echo -ne "\n"
echo -ne "Installing pip-save...\n"

# ~/.zshrc, ~/.bashrc
SHELL_RC_FILE="$HOME/.$(basename $SHELL)rc"
COUNT=0
IFS=':' read -ra PATHS <<< "$PATH"

export PATH=$HOME/bin:$PATH
echo 'export PATH=$HOME/bin:$PATH' >> $SHELL_RC_FILE

[ $(grep -e "pipsave_line" ~/.zshrc | wc -l) == 0 ] && echo '[ -f ~/.pipsave_cd ] && source ~/.pipsave_cd # pipsave_line' >> $SHELL_RC_FILE

export WORKON_HOME=~/.virtualenvs
source /usr/local/bin/virtualenvwrapper.sh

[ -z $WORKON_HOME ] && echo "export WORKON_HOME=~/.virtualenvs" >> $SHELL_RC_FILE
[ -z $VIRTUALENVWRAPPER_SCRIPT ] && echo "source /usr/local/bin/virtualenvwrapper.sh" >> $SHELL_RC_FILE

mkdir -p $HOME/bin

curl -sSLk -o $HOME/bin/pip3 "https://raw.githubusercontent.com/abhiomkar/pip-save/master/bin/pip3" && \
curl -sSLk -o $HOME/.pipsave_cd "https://raw.githubusercontent.com/abhiomkar/pip-save/master/src/pipsave_cd" && \
echo -e ">>> Installation successful"
chmod +x $HOME/bin/pip3
